print("Create your character!")
name = input("what is your character called? ")
age = input("how old is your character? ")
strengths = input("what are your characters strengths? ")
weaknesses = input("what are your characters weaknesses? ")
race = input("what is your characters race? ")
print("your characters name is: ", name)
print("your character is ", age, "years old")
print("strengths: ", strengths)
print("weaknesses: ", weaknesses)
print("your characters race is: ", race)
print(name, "says hello")